// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qjkXYzImLhy5NRDOFn4f9jy6WXwcvdk',
    appId: '1:44063230213:web:ebecf8b334ccbf37e50f6c',
    messagingSenderId: '44063230213',
    projectId: 'calci-devsoc',
    authDomain: 'calci-devsoc.firebaseapp.com',
    storageBucket: 'calci-devsoc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwcziqXPApQ1nDxulZXr9__YKjYoOfmbU',
    appId: '1:44063230213:android:5b5a7b5c5036f345e50f6c',
    messagingSenderId: '44063230213',
    projectId: 'calci-devsoc',
    storageBucket: 'calci-devsoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR4o_OIncowMTqfgxY4gXR6mJwEV28x7w',
    appId: '1:44063230213:ios:b14402bbe95c0350e50f6c',
    messagingSenderId: '44063230213',
    projectId: 'calci-devsoc',
    storageBucket: 'calci-devsoc.appspot.com',
    iosBundleId: 'com.example.calculatorDevsoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR4o_OIncowMTqfgxY4gXR6mJwEV28x7w',
    appId: '1:44063230213:ios:b14402bbe95c0350e50f6c',
    messagingSenderId: '44063230213',
    projectId: 'calci-devsoc',
    storageBucket: 'calci-devsoc.appspot.com',
    iosBundleId: 'com.example.calculatorDevsoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5qjkXYzImLhy5NRDOFn4f9jy6WXwcvdk',
    appId: '1:44063230213:web:abe520bf0bcf0c7fe50f6c',
    messagingSenderId: '44063230213',
    projectId: 'calci-devsoc',
    authDomain: 'calci-devsoc.firebaseapp.com',
    storageBucket: 'calci-devsoc.appspot.com',
  );
}
